# Generated by Django 4.2.2 on 2023-07-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_pv_post_uv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
