# Generated by Django 4.2.2 on 2023-07-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_category_options_alter_tag_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_html',
            field=models.TextField(blank=True, editable=False, verbose_name='正文html'),
        ),
    ]
